### ISSUE TITLE
Key generator

### ISSUE THREAD

**Issue by wolfshtein** [evilsoft/webdev-multitool#3]
Thx for the tips, just a question : Where is the key generator

**Comment by evilsoft** [comment]
@wolfshtein Are you asking where I get the keys from, I am using `node-uuid`, I bring it into the main process here:
https://github.com/evilsoft/webdev-multitool/blob/master/src/main/app.js#L11

And to messages, via electrons IPC here:
https://github.com/evilsoft/webdev-multitool/blob/master/src/main/app.js#L31

After setting up the function here:
https://github.com/evilsoft/webdev-multitool/blob/master/src/main/app.js#L20

That functions sends the response that is picked up in the render process and dispatches to redux here:
https://github.com/evilsoft/webdev-multitool/blob/master/src/render/js/app.js#L12
